# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
import sys
import time
class Solution(object):

    @staticmethod
    def generate_fibonacci_even(threshold, first_num, second_num):
        total = 0
        even_tally = 0
        while total < threshold:
            if total % 2 == 0:
                even_tally += total
            total = first_num + second_num
            first_num = second_num
            second_num = total
        return even_tally

def main():
    threshold = int(sys.argv[1])
    first_num = int(sys.argv[2])
    second_num = int(sys.argv[3])
    start = time.perf_counter()
    solution = Solution.generate_fibonacci_even(threshold, first_num, second_num)
    end = time.perf_counter()
    print(solution)
    print(start - end)


main()
